### ISSUE TITLE
Add a loading screen

### ISSUE THREAD

**Issue by jaks6** [jaks6/WebGL-Billiards#2]
Load textures and setup the scene before actually showing the canvas

**Comment by jaks6** [comment]
Some progress on this was made in 0fe6598975eaee35d4d69f88d944f239f3e5e8bf,
however, it could be improved. The nicest way would be to have something overlaid on the canvas or have the dimensions of the canvas, instead of the way it is implemented currently, where a narrow progress bar is first shown, then hidden, and replaced with the large canvas.

**Comment by Ingramz** [comment]
It's nicely overlaid now.
